version: 2

updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/examples"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/release/oci-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/release/oci-runtime"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
